# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_hstore'),
        ('users', '0002_auto_20161027_1323'),
    ]

    operations = [
    ]
