# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 17:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20161028_1424'),
        ('users', '0004_merge_20170403_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.User')),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3)),
                ('static_weight', models.FloatField()),
            ],
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='CompanyConfidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryConfidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bot')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
